<?php return array (
  'text' => '#444444',
  'link' => '#f08e3e',
  'btn' => '#f08e3e',
  'btn_text' => '#ffffff',
  'bg_page' => '#383838',
  'bg_header' => '#f08e3e',
  'bg_body' => '#ffffff',
  'bg_footer' => '#ededed',
  'text_top' => '#ffffff',
  'text_head' => '#ffffff',
  'text_foot' => '#444444',
  'text_bottom' => '#ffffff',
  'link_top' => '#f08e3e',
  'link_head' => '#f08e3e',
  'link_foot' => '#f08e3e',
  'link_bottom' => '#f08e3e',
);