<?php return array (
  'btn' => '#2dc4f0',
  'btn_text' => '#fff',
  'bg_page' => '#383838',
  'text_top' => '#fff',
  'text_head' => '#444',
  'link_top' => '#2dc4f0',
  'link_head' => '#2dc4f0',
  'bg_header' => '#fff',
  'text' => '#444444',
  'link' => '#2dc4f0',
  'bg_body' => '#fff',
  'text_foot' => '#444444',
  'text_bottom' => '#fff',
  'link_foot' => '#2dc4f0',
  'link_bottom' => '#2dc4f0',
  'bg_footer' => '#ededed',
);